version: '3.7'

services:
  movie_service:
    build: ./movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URI=sqlite:////app/movie_service.db  # pour movie_service
    volumes:
      - ./movie-service/:/app/
      - ./movie_service.db:/app/movie_service.db  # Persist le fichier de base de données
    ports:
      - 8001:8000

  cast_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URI=sqlite:////app/cast_service.db  # pour cast_service
    volumes:
      - ./cast-service/:/app/
      - ./cast_service.db:/app/cast_service.db  # Persist le fichier de base de données
    ports:
      - 8002:8000

  nginx:
    image: nginx:latest
    ports:
      - "8081:8080"
    volumes:
      - ./nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

volumes: {}
