apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fastapi.fullname" . }}
  labels:
    {{- include "fastapi.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    {{- range .Values.ingress.hosts }}  # Itère sur chaque hôte défini
    - host: {{ .host }}  # Utilise l'hôte actuel
      http:
        paths:
          {{- range .paths }}  # Itère sur les chemins pour cet hôte
          - path: {{ . }}  # Utilise le chemin courant
            pathType: {{ $.Values.ingress.pathType }}  # Utilise le pathType général
            backend:
              service:
                name: {{ include "fastapi.fullname" $ }}  # Garde le contexte
                port:
                  number: {{ $.Values.service.port }} 
          {{- end }}
    {{- end }}
