apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}  # Utilisez le modèle défini
  labels:
    {{- include "fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "fastapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
