# Utiliser l'image officielle de Nginx
FROM nginx:latest

# Copier le fichier de configuration Nginx dans l'image
COPY nginx_config.conf /etc/nginx/conf.d/default.conf

# Exposer le port 8080
EXPOSE 8080
