replicaCount: 1

image:
  repository: ameliendevops
  pullPolicy: IfNotPresent
  tag: latest

service:
  enabled: true
  name: service
  port: 80
  targetPort: 8000
  type: ClusterIP

ingress:
  enabled: true
  name: ""
  path: /
  pathType: ImplementationSpecific
  hosts:
    - host: chart-example.local
      paths:
        - /

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources: {}
